Backend: Vivado
Board: null
ClockPeriod: 5
HLSConfig:
  Model:
    Precision: ap_fixed<32,16>
    ReuseFactor: 10000
    Strategy: Resource
IOType: io_stream
InputData: null
KerasModel: !keras_model 'unet_test/keras_model.h5'
OutputDir: unet_test
OutputPredictions: null
ProjectName: myproject
Stamp: E3816B1D
XilinxPart: xczu9eg-ffvb1156-2-e
